### ISSUE TITLE
Ionic2

### ISSUE THREAD

**Issue by OmarHassan25** [tjoskar/ng2-lazyload-image#1] opened 2016-04-10 13:32 UTC
I need to use your plugin with cordoca/ionic2 typescript app, When trying to add the providers i am getting this error, Parse Error: 'import' and 'export' may appear only with 'sourceType: module'

Could you please help in how i can use it with ionic2 typescript.

**Comment by tjoskar** [comment] 2016-04-11 09:10
I'm not very familiar with ionic2, but I will take a look tonight. 

1. Are you using typescript? Which version?
2. Do you get the error under compilation or runtime?
3. Can you provide a an example of how you are using the addon?

**Comment by tjoskar** [comment] 2016-04-21 05:32
Hi,

I can't reproduce the error. How do you install the packaged? Can you provide any snippet?

I created a demo project:
```bash
$ ionic start ionic-lazy-load-images --v2
$ cd ionic-lazy-load-images
$ npm install ng2-lazyload-image@1.1.0 --save
$ ionic serve
```
and updated `app/pages/page1/page1.js`: 
```javascript
import { Page } from 'ionic-angular';
import { LazyLoadImageDirective } from 'ng2-lazyload-image';

@Page({
  templateUrl: 'build/pages/page1/page1.html',
  directives: [ LazyLoadImageDirective ]
})
export class Page1 {
  constructor() {
    this.defaultImage = 'https://www.placecage.com/1000/1000';
    this.image = 'https://images.unsplash.com/photo-1443890923422-7819ed4101c0?fm=jpg';
    this.offset = 100;
  }
}
```

and `app/pages/page1/page1.html`:
```html
<ion-navbar *navbar>
  <ion-title>Tab 1</ion-title>
</ion-navbar>

<ion-content padding class="page1" #container>
  <h2>Welcome to Ionic!</h2>
  <p style="height: 1000px;">
    This starter project comes with simple tabs-based layout for apps
    that are going to primarily use a Tabbed UI.
  </p>
  <img [src]="defaultImage" [lazyLoad]="image" [offset]="offset" [scrollTarget]="container.scrollElement">
</ion-content>
```

And it seems to work fine :)

**Comment by tjoskar** [comment] 2016-05-12 17:16
@OmarHassan25, I close this issue. Feel free to reopening it if you don't get it to work.

**Closed by tjoskar** 2016-05-12 17:16 UTC
